// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from '../../app/server'

export type PageName = 'About' | 'Counter' | 'Home' | 'Users/Index' | 'Users/Show'

declare module '@hono/inertia' {
  interface InertiaPages {
    'About': unknown
    'Counter': unknown
    'Home': unknown
    'Users/Index': unknown
    'Users/Show': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
