// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './server'

export type PageName = 'Counter' | 'Home' | 'Users/Index' | 'Users/New' | 'Users/Show'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Counter': unknown
    'Home': unknown
    'Users/Index': unknown
    'Users/New': unknown
    'Users/Show': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
